---
- hosts: all
  gather_facts: false
  tasks:
    - name: espera ssh
      wait_for_connection:
        delay: 10
        sleep: 5
        timeout: 300
      vars:
        ansible_user: ec2-user

- hosts: all
  vars:
    ansible_user: ec2-user
  tasks:
    - name: Intalando Apache Https
      yum:
       name: httpd
       state: latest
       become: yes
    - name: Enabled httpd
      service:
        name: httpd
        enabled: true
        state: started
    - name: Install app
      copy:
        src: /home/sinensia/hello-2048
        dest: /var/www/html/
        owner: apache
        group: apache
        mode: "0644"
        directory_mode: "0755"
